# Generated by Django 3.0.2 on 2020-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creatname', models.CharField(max_length=50)),
                ('subnum', models.CharField(max_length=10)),
                ('like', models.IntegerField()),
                ('live', models.BooleanField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
            ],
        ),
    ]
